<TopBar>:
    name:"topbar"

    MDTopAppBar:
        id:topbar
        title: "teste internet"
        pos_hint: {"center_x": .5, "top": 1.0/1.0}
        type: "top"
        right_action_items: [[app.get_icon(),lambda x:  app.switch_theme()]]
        left_action_items: [["menu",lambda x:  root.callback(x)]]

    MDRaisedButton: 
        id: menu_button 
        text: "Menu" 
        on_release: root.menu.open()


